//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GinClientApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GinClientApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Open the repository browser.
        /// </summary>
        internal static string CreateNewRepoDlg_Open_the_repository_browser {
            get {
                return ResourceManager.GetString("CreateNewRepoDlg_Open_the_repository_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Login failed.
        /// </summary>
        internal static string GetUserCredentials_Login_Failed {
            get {
                return ResourceManager.GetString("GetUserCredentials_Login_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Login unsuccessful. Username or password are incorrect.
        /// </summary>
        internal static string GetUserCredentials_Login_Unsuccessful {
            get {
                return ResourceManager.GetString("GetUserCredentials_Login_Unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný The entered Username/Password combination is invalid.
        /// </summary>
        internal static string GetUserCredentials_The_entered_Username_Password_combination_is_invalid {
            get {
                return ResourceManager.GetString("GetUserCredentials_The_entered_Username_Password_combination_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Icon podobný (Ikona).
        /// </summary>
        internal static System.Drawing.Icon gin_icon {
            get {
                object obj = ResourceManager.GetObject("gin_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Icon podobný (Ikona).
        /// </summary>
        internal static System.Drawing.Icon gin_icon_desaturated {
            get {
                object obj = ResourceManager.GetObject("gin_icon_desaturated", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gin_icon_desaturated1 {
            get {
                object obj = ResourceManager.GetObject("gin_icon_desaturated1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný About.
        /// </summary>
        internal static string GinApplicationContext_About {
            get {
                return ResourceManager.GetString("GinApplicationContext_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Error while trying to access Gin Client Service.
        /// </summary>
        internal static string GinApplicationContext_Error_while_trying_to_access_Gin_Client_Service {
            get {
                return ResourceManager.GetString("GinApplicationContext_Error_while_trying_to_access_Gin_Client_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Error while trying to log in to GIN.
        /// </summary>
        internal static string GinApplicationContext_Error_while_trying_to_log_in_to_GIN {
            get {
                return ResourceManager.GetString("GinApplicationContext_Error_while_trying_to_log_in_to_GIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Exit.
        /// </summary>
        internal static string GinApplicationContext_Exit {
            get {
                return ResourceManager.GetString("GinApplicationContext_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Retrieving {0} from repository {1}.
        /// </summary>
        internal static string GinApplicationContext_FileOperation_Retrieving {
            get {
                return ResourceManager.GetString("GinApplicationContext_FileOperation_Retrieving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Gin Client Error.
        /// </summary>
        internal static string GinApplicationContext_Gin_Client_Error {
            get {
                return ResourceManager.GetString("GinApplicationContext_Gin_Client_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Gin Service Error.
        /// </summary>
        internal static string GinApplicationContext_Gin_Service_Error {
            get {
                return ResourceManager.GetString("GinApplicationContext_Gin_Service_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Gin Service has stopped communicating..
        /// </summary>
        internal static string GinApplicationContext_Gin_Service_has_stopped_communicating_ {
            get {
                return ResourceManager.GetString("GinApplicationContext_Gin_Service_has_stopped_communicating_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Manage Repositories.
        /// </summary>
        internal static string GinApplicationContext_Manage_Repositories {
            get {
                return ResourceManager.GetString("GinApplicationContext_Manage_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Mount.
        /// </summary>
        internal static string GinApplicationContext_Mount {
            get {
                return ResourceManager.GetString("GinApplicationContext_Mount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Options.
        /// </summary>
        internal static string GinApplicationContext_Options {
            get {
                return ResourceManager.GetString("GinApplicationContext_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný GIN Repository activity in progress.
        /// </summary>
        internal static string GinApplicationContext_Repository_Activity {
            get {
                return ResourceManager.GetString("GinApplicationContext_Repository_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Unmount.
        /// </summary>
        internal static string GinApplicationContext_Unmount {
            get {
                return ResourceManager.GetString("GinApplicationContext_Unmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Update.
        /// </summary>
        internal static string GinApplicationContext_Update {
            get {
                return ResourceManager.GetString("GinApplicationContext_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Upload changes.
        /// </summary>
        internal static string GinApplicationContext_Upload {
            get {
                return ResourceManager.GetString("GinApplicationContext_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný About.
        /// </summary>
        internal static string GinAppRepo_About {
            get {
                return ResourceManager.GetString("GinAppRepo_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Address.
        /// </summary>
        internal static string GinAppRepo_ColumnAddress {
            get {
                return ResourceManager.GetString("GinAppRepo_ColumnAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Checkout Directory.
        /// </summary>
        internal static string GinAppRepo_ColumnCheckout {
            get {
                return ResourceManager.GetString("GinAppRepo_ColumnCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Mountpoint.
        /// </summary>
        internal static string GinAppRepo_ColumnMount {
            get {
                return ResourceManager.GetString("GinAppRepo_ColumnMount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Name.
        /// </summary>
        internal static string GinAppRepo_ColumnName {
            get {
                return ResourceManager.GetString("GinAppRepo_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Gin Client Version.
        /// </summary>
        internal static string GinAppRepo_GinVersion {
            get {
                return ResourceManager.GetString("GinAppRepo_GinVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný License Information.
        /// </summary>
        internal static string GinAppRepo_LicenseInfo {
            get {
                return ResourceManager.GetString("GinAppRepo_LicenseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Gin Client Warning.
        /// </summary>
        internal static string GinClientApp_Gin_Client_Warning {
            get {
                return ResourceManager.GetString("GinClientApp_Gin_Client_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný BSD 3-Clause License
        ///
        ///Copyright (c) 2019, German Neuroinformatics Node (G-Node)
        ///                    
        ///All rights reserved.
        ///
        ///Redistribution and use in source and binary forms, with or without
        ///modification, are permitted provided that the following conditions are met:
        ///
        ///* Redistributions of source code must retain the above copyright notice, this
        ///  list of conditions and the following disclaimer.
        ///
        ///* Redistributions in binary form must reproduce the above copyright notice,
        ///  this list of conditions  [zbytek řetězce byl zkrácen];.
        /// </summary>
        internal static string License_Text {
            get {
                return ResourceManager.GetString("License_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Choose a directory for the checkout.
        /// </summary>
        internal static string MetroCreateNewRepoDlg_Choose_a_directory_for_the_checkout {
            get {
                return ResourceManager.GetString("MetroCreateNewRepoDlg_Choose_a_directory_for_the_checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Choose a directory for the mountpoint.
        /// </summary>
        internal static string MetroCreateNewRepoDlg_Choose_a_directory_for_the_mountpoint {
            get {
                return ResourceManager.GetString("MetroCreateNewRepoDlg_Choose_a_directory_for_the_mountpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný &lt;username&gt;/&lt;repository&gt;.
        /// </summary>
        internal static string Options__username___repository_ {
            get {
                return ResourceManager.GetString("Options__username___repository_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný A Repository with that address already exists.
        /// </summary>
        internal static string Options_CheckSanity_A_repository_with_this_name_exists {
            get {
                return ResourceManager.GetString("Options_CheckSanity_A_repository_with_this_name_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Could not retrieve repository info for this repository. Are you sure the name is spelt correctly?.
        /// </summary>
        internal static string Options_CheckSanity_Could_not_retrieve_repo_info {
            get {
                return ResourceManager.GetString("Options_CheckSanity_Could_not_retrieve_repo_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný No checkout address has been entered..
        /// </summary>
        internal static string Options_CheckSanity_No_checkout_address_has_been_entered_ {
            get {
                return ResourceManager.GetString("Options_CheckSanity_No_checkout_address_has_been_entered_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný No private or shared repositories with this address exist.
        /// </summary>
        internal static string Options_CheckSanity_No_private_or_shared_repos {
            get {
                return ResourceManager.GetString("Options_CheckSanity_No_private_or_shared_repos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný The checkout directory {0} must be empty..
        /// </summary>
        internal static string Options_CheckSanity_The_checkout_address_is_not_empty {
            get {
                return ResourceManager.GetString("Options_CheckSanity_The_checkout_address_is_not_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný The checkout address is not properly formatted. Do you wish to create a new repository with the name {0} instead?.
        /// </summary>
        internal static string Options_CheckSanity_The_checkout_address_is_not_properly_formatted {
            get {
                return ResourceManager.GetString("Options_CheckSanity_The_checkout_address_is_not_properly_formatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný The checkout directory already exists. Do you wish to delete it?.
        /// </summary>
        internal static string Options_CheckSanity_The_checkout_directory_already_exists {
            get {
                return ResourceManager.GetString("Options_CheckSanity_The_checkout_directory_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný The mountpoint and checkout directory can not be subdirectories of each other..
        /// </summary>
        internal static string Options_CheckSanity_The_mountpoint_and_checkout_directory_can_not_be_subdirectories {
            get {
                return ResourceManager.GetString("Options_CheckSanity_The_mountpoint_and_checkout_directory_can_not_be_subdirectori" +
                        "es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný The mountpoint directory already exists. Do you wish to delete it?.
        /// </summary>
        internal static string Options_CheckSanity_The_mountpoint_directory_already_exists {
            get {
                return ResourceManager.GetString("Options_CheckSanity_The_mountpoint_directory_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný This will delete the repository {0} and all associated data. Do you wish to continue?.
        /// </summary>
        internal static string Options_This_will_delete_the_repository {
            get {
                return ResourceManager.GetString("Options_This_will_delete_the_repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný This will delete the selected Repository and all associated data. Continue?.
        /// </summary>
        internal static string RepoManagement_Delete_repository {
            get {
                return ResourceManager.GetString("RepoManagement_Delete_repository", resourceCulture);
            }
        }
    }
}
